name: Generate GitHub Trophies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: RahulKuVerma
          file: trophy.svg
          token: ${{ secrets.TROPHY_TOKEN }}
          theme: algolia
          max-cols: 4
          max-rows: 3
          margin-width: 15
          margin-height: 15
          no-background: true
          no-frame: true

      - name: Check Trophy
        run: |
          echo "Checking generated trophy.svg..."
          ls -lh trophy.svg

      - name: Commit Trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add trophy.svg

          if git diff --cached --quiet; then
            echo "No changes to trophy.svg"
          else
            git commit -m "Update GitHub trophies"
            git push origin main
          fi
